// Package main is to create tables for importing data generated by scorer/cmd.
// The command-line interface requires a preset name as the first argument.
package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"

	"github.com/GoogleCloudPlatform/cloudsql-proxy/proxy/dialers/mysql"
)

// TODO: Parameterize these constants
const (
	instance = "nijk-225007:asia-northeast1:nijk-master"
	user     = "nijk"
)

var preset string = os.Args[1]

type binDB struct {
	db   *sql.DB
	last string
	err  error
}

// Exec is a wrapper function which executes sql.DB.Exec and keep its error,
// when only there was no error before.
func (bdb *binDB) Exec(query string, args ...interface{}) {
	if bdb.err == nil {
		_, err := bdb.db.Exec(query, args...)
		bdb.last = query
		bdb.err = err
	}
}

func main() {
	cfg := mysql.Cfg(instance, user, "")
	cfg.DBName = "nijk"
	db, err := mysql.DialCfg(cfg)
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	bdb := binDB{db, "", nil}
	for _, relation := range []string{"paradigmatic", "syntagmatic"} {
		bdb.Exec(dropTable(preset, relation))
		bdb.Exec(createTable(preset, relation))
	}

	if bdb.err != nil {
		log.Fatal(bdb.err)
	}
}

func dropTable(preset, relation string) string {
	table := fmt.Sprintf("`%s_%s`", preset, relation)
	template := `
DROP TABLE IF EXISTS %s`
	return fmt.Sprintf(template, table)
}

func createTable(preset, relation string) string {
	table := fmt.Sprintf("`%s_%s`", preset, relation)
	template := `
CREATE TABLE %s
(
  this   VARCHAR(128),
  that   VARCHAR(128),
  score  DOUBLE NOT NULL,
  PRIMARY KEY (this, that),
  INDEX (this, score)
);`
	return fmt.Sprintf(template, table)
}
